#!/usr/bin/env sh
set -e

unformatted=$(gofmt -l cmd internal)
if [ -n "$unformatted" ]; then
	echo "gofmt: needs formatting (run 'make fmt'):"
	echo "$unformatted"
	exit 1
fi

prettier --check '**/*.md'
golangci-lint run
go test ./...
