version: "2"

linters:
  default: standard
  enable:
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nikbrunner/tsm

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
