// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-mono-dark",
		Appearance: "dark",

		BgSelection: "#2b2826",
		BgContrast:  "#c6c3c1",
		BgNegative:  "#502d2d",

		FgDefault:  "#edeae8",
		FgSubtle:   "#82807d",
		FgAccent:   "#e4e4e4",
		FgDisabled: "#656360",
		FgContrast: "#0f0d0b",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow: "#82807d",
		PaletteGreen:  "#82807d",
		PaletteRed:    "#a09e9b",
		PaletteBlue:   "#a09e9b",
	})
}
