// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-jpn-tsuki-yoru",
		Appearance: "dark",

		BgSelection: "#373737",
		BgContrast:  "#e6e6e6",
		BgNegative:  "#6b4853",

		FgDefault:  "#e6e6e6",
		FgSubtle:   "#9d9daf",
		FgAccent:   "#eab899",
		FgDisabled: "#828299",
		FgContrast: "#1c1c1c",
		FgNegative: "#f591b2",
		FgInfo:     "#a1b0cf",
		FgAdd:      "#90b99f",
		FgDelete:   "#f591b2",

		PaletteYellow:      "#eab899",
		PaletteGreen:       "#90b99f",
		PaletteRed:         "#f591b2",
		PaletteBlue:        "#a1b0cf",
		PaletteMagenta:     "#aca1cf",
		PaletteDarkMagenta: "#9789c3",
	})
}
