// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-default-dark",
		Appearance: "dark",

		BgSelection: "#25292f",
		BgContrast:  "#d2d8df",
		BgNegative:  "#5c333d",

		FgDefault:  "#e5ecf3",
		FgSubtle:   "#7b8187",
		FgAccent:   "#4ec983",
		FgDisabled: "#6a6f76",
		FgContrast: "#12171b",
		FgNegative: "#e97292",
		FgInfo:     "#00b9c3",
		FgAdd:      "#4cb86a",
		FgDelete:   "#e97292",

		PaletteYellow:      "#7b8187",
		PaletteGreen:       "#8d9399",
		PaletteRed:         "#8d9399",
		PaletteBlue:        "#6a6f76",
		PaletteMagenta:     "#7faaff",
		PaletteDarkMagenta: "#fb82a1",
	})
}
