// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-eink-light",
		Appearance: "light",

		BgSelection: "#c4c4c4",
		BgContrast:  "#4d4d4d",
		BgNegative:  "#f3c7c3",

		FgDefault:  "#292929",
		FgSubtle:   "#5d5d5d",
		FgAccent:   "#5f5155",
		FgDisabled: "#8c8c8c",
		FgContrast: "#d1d1d1",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#8c8c8c",
		PaletteGreen:       "#8c8c8c",
		PaletteRed:         "#a4a4a4",
		PaletteBlue:        "#a4a4a4",
		PaletteMagenta:     "#8c8c8c",
		PaletteDarkMagenta: "#8c8c8c",
	})
}
