// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-jpn-koyo-yoru",
		Appearance: "dark",

		BgSelection: "#4a3d50",
		BgContrast:  "#ead2b2",
		BgNegative:  "#714649",

		FgDefault:  "#ead2b2",
		FgSubtle:   "#b19b7c",
		FgAccent:   "#e49e22",
		FgDisabled: "#927c5f",
		FgContrast: "#261a2a",
		FgNegative: "#fe838f",
		FgInfo:     "#b5a4d7",
		FgAdd:      "#7fc08c",
		FgDelete:   "#fe838f",

		PaletteYellow:      "#e49e22",
		PaletteGreen:       "#7fc08c",
		PaletteRed:         "#fe838f",
		PaletteBlue:        "#b5a4d7",
		PaletteMagenta:     "#e19b73",
		PaletteDarkMagenta: "#c07d55",
	})
}
