// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-jpn-murasaki-yoru",
		Appearance: "dark",

		BgSelection: "#5b3e47",
		BgContrast:  "#d4bfd6",
		BgNegative:  "#754a45",

		FgDefault:  "#d4bfd6",
		FgSubtle:   "#946996",
		FgAccent:   "#dca23a",
		FgDisabled: "#865f88",
		FgContrast: "#351b23",
		FgNegative: "#ff857b",
		FgInfo:     "#8cb6c5",
		FgAdd:      "#80bda2",
		FgDelete:   "#ff857b",

		PaletteYellow:      "#dca23a",
		PaletteGreen:       "#80bda2",
		PaletteRed:         "#ff857b",
		PaletteBlue:        "#8cb6c5",
		PaletteMagenta:     "#d49bb2",
		PaletteDarkMagenta: "#b9a2d4",
	})
}
