// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-clay-dark",
		Appearance: "dark",

		BgSelection: "#4a4842",
		BgContrast:  "#c2beac",
		BgNegative:  "#674242",

		FgDefault:  "#e3decc",
		FgSubtle:   "#a49e8d",
		FgAccent:   "#fc8a61",
		FgDisabled: "#868070",
		FgContrast: "#302e28",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow: "#a49e8d",
		PaletteGreen:  "#a49e8d",
		PaletteRed:    "#b4ae9c",
		PaletteBlue:   "#b4ae9c",
	})
}
