// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-paper-brown-light",
		Appearance: "light",

		BgSelection: "#decfba",
		BgContrast:  "#4e463d",
		BgNegative:  "#f8cdc8",

		FgDefault:  "#2b2826",
		FgSubtle:   "#7a7062",
		FgAccent:   "#242424",
		FgDisabled: "#aa9c8a",
		FgContrast: "#e8d8c4",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow: "#aa9c8a",
		PaletteGreen:  "#aa9c8a",
		PaletteRed:    "#c4b5a1",
		PaletteBlue:   "#c4b5a1",
	})
}
