// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-mikado-light",
		Appearance: "light",

		BgSelection: "#a8b9c0",
		BgContrast:  "#2d404b",
		BgNegative:  "#e5bab6",

		FgDefault:  "#0f212d",
		FgSubtle:   "#4c5d67",
		FgAccent:   "#cc8f00",
		FgDisabled: "#617683",
		FgContrast: "#b4c3c9",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#617683",
		PaletteGreen:       "#617683",
		PaletteRed:         "#7b919d",
		PaletteBlue:        "#cc8f00",
		PaletteMagenta:     "#617683",
		PaletteDarkMagenta: "#617683",
	})
}
