// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-winter-night",
		Appearance: "dark",

		BgSelection: "#212f3f",
		BgContrast:  "#e2e8f2",
		BgNegative:  "#444459",

		FgDefault:  "#e2e8f2",
		FgSubtle:   "#6f8298",
		FgAccent:   "#fba952",
		FgDisabled: "#5e748b",
		FgContrast: "#12161d",
		FgNegative: "#a8a6e5",
		FgInfo:     "#7fb6ee",
		FgAdd:      "#82c3d3",
		FgDelete:   "#a8a6e5",

		PaletteYellow: "#fba952",
		PaletteGreen:  "#82c3d3",
		PaletteRed:    "#a8a6e5",
		PaletteBlue:   "#7fb6ee",
	})
}
