// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-stations-operations",
		Appearance: "dark",

		BgSelection: "#354e46",
		BgContrast:  "#c1efd5",
		BgNegative:  "#75515f",

		FgDefault:  "#c1efd5",
		FgSubtle:   "#91bcad",
		FgAccent:   "#b7db6e",
		FgDisabled: "#75a490",
		FgContrast: "#21302d",
		FgNegative: "#f08cb4",
		FgInfo:     "#abe7ca",
		FgAdd:      "#80c980",
		FgDelete:   "#f08cb4",

		PaletteYellow: "#b7db6e",
		PaletteGreen:  "#80c980",
		PaletteRed:    "#f08cb4",
		PaletteBlue:   "#abe7ca",
	})
}
