// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-paper-blue-dark",
		Appearance: "dark",

		BgSelection: "#224c6a",
		BgContrast:  "#d1d9df",
		BgNegative:  "#633e3e",

		FgDefault:  "#eef2f5",
		FgSubtle:   "#839caf",
		FgAccent:   "#f2f6f9",
		FgDisabled: "#5f7f95",
		FgContrast: "#002b51",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow: "#839caf",
		PaletteGreen:  "#839caf",
		PaletteRed:    "#a7bac9",
		PaletteBlue:   "#a7bac9",
	})
}
