// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-jpn-koyo-hiru",
		Appearance: "light",

		BgSelection: "#f8e7d0",
		BgContrast:  "#3a2e3b",
		BgNegative:  "#fccbcd",

		FgDefault:  "#3a2e3b",
		FgSubtle:   "#b19b7c",
		FgAccent:   "#ed9a00",
		FgDisabled: "#d1ba9b",
		FgContrast: "#fef2e1",
		FgNegative: "#f5345e",
		FgInfo:     "#9e77dc",
		FgAdd:      "#3aa85b",
		FgDelete:   "#f5345e",

		PaletteYellow:      "#ed9a00",
		PaletteGreen:       "#3aa85b",
		PaletteRed:         "#f5345e",
		PaletteBlue:        "#9e77dc",
		PaletteMagenta:     "#f88f4f",
		PaletteDarkMagenta: "#f2943c",
	})
}
