// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-default-light-dimmed",
		Appearance: "light",

		BgSelection: "#bec5cc",
		BgContrast:  "#3e4349",
		BgNegative:  "#f6c9da",

		FgDefault:  "#20252a",
		FgSubtle:   "#595e64",
		FgAccent:   "#2eaf6b",
		FgDisabled: "#7b8187",
		FgContrast: "#cbd2d9",
		FgNegative: "#ff50a7",
		FgInfo:     "#00abc1",
		FgAdd:      "#00a800",
		FgDelete:   "#ff50a7",

		PaletteYellow:      "#7b8187",
		PaletteGreen:       "#8d9399",
		PaletteRed:         "#6a6f76",
		PaletteBlue:        "#6a6f76",
		PaletteMagenta:     "#6791f1",
		PaletteDarkMagenta: "#df6989",
	})
}
