// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-paper-blue-light",
		Appearance: "light",

		BgSelection: "#c5cbd2",
		BgContrast:  "#004f8b",
		BgNegative:  "#ffd4cf",

		FgDefault:  "#002469",
		FgSubtle:   "#32669a",
		FgAccent:   "#002469",
		FgDisabled: "#558ac0",
		FgContrast: "#dadee3",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#558ac0",
		PaletteGreen:       "#558ac0",
		PaletteRed:         "#679dd4",
		PaletteBlue:        "#679dd4",
		PaletteMagenta:     "#558ac0",
		PaletteDarkMagenta: "#558ac0",
	})
}
