// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-stations-engineering",
		Appearance: "dark",

		BgSelection: "#2a3535",
		BgContrast:  "#d5f4e3",
		BgNegative:  "#65424f",

		FgDefault:  "#d5f4e3",
		FgSubtle:   "#91bcad",
		FgAccent:   "#c6de68",
		FgDisabled: "#75a490",
		FgContrast: "#0d1818",
		FgNegative: "#f08cb4",
		FgInfo:     "#c3eed9",
		FgAdd:      "#7fcd81",
		FgDelete:   "#f08cb4",

		PaletteYellow:      "#c6de68",
		PaletteGreen:       "#7fcd81",
		PaletteRed:         "#f08cb4",
		PaletteBlue:        "#c3eed9",
		PaletteMagenta:     "#a5a9e5",
		PaletteDarkMagenta: "#999fdb",
	})
}
