// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-stations-research",
		Appearance: "light",

		BgSelection: "#e3e8e6",
		BgContrast:  "#2b3b33",
		BgNegative:  "#fcd8e2",

		FgDefault:  "#2b3b33",
		FgSubtle:   "#75a490",
		FgAccent:   "#66bd10",
		FgDisabled: "#95b8ac",
		FgContrast: "#f8f9f9",
		FgNegative: "#f472a0",
		FgInfo:     "#51796d",
		FgAdd:      "#53aa53",
		FgDelete:   "#f472a0",

		PaletteYellow: "#66bd10",
		PaletteGreen:  "#53aa53",
		PaletteRed:    "#f472a0",
		PaletteBlue:   "#51796d",
	})
}
