// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-stations-medical",
		Appearance: "light",

		BgSelection: "#c6d1cc",
		BgContrast:  "#2b3b33",
		BgNegative:  "#edcad3",

		FgDefault:  "#2b3b33",
		FgSubtle:   "#669a84",
		FgAccent:   "#66bd10",
		FgDisabled: "#77a494",
		FgContrast: "#e1e7e4",
		FgNegative: "#f472a0",
		FgInfo:     "#476a5f",
		FgAdd:      "#3c8e3c",
		FgDelete:   "#f472a0",

		PaletteYellow: "#66bd10",
		PaletteGreen:  "#3c8e3c",
		PaletteRed:    "#f472a0",
		PaletteBlue:   "#476a5f",
	})
}
