// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-orange-light",
		Appearance: "light",

		BgSelection: "#e8eced",
		BgContrast:  "#474e51",
		BgNegative:  "#ffd5d1",

		FgDefault:  "#242a2c",
		FgSubtle:   "#585f61",
		FgAccent:   "#fc8e06",
		FgDisabled: "#868e90",
		FgContrast: "#eef3f4",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#fc8e06",
		PaletteGreen:       "#868e90",
		PaletteRed:         "#9ea6a9",
		PaletteBlue:        "#9ea6a9",
		PaletteMagenta:     "#868e90",
		PaletteDarkMagenta: "#868e90",
	})
}
