// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-clay-light",
		Appearance: "light",

		BgSelection: "#ddd8c2",
		BgContrast:  "#4c473c",
		BgNegative:  "#fed2cd",

		FgDefault:  "#322e22",
		FgSubtle:   "#5d553f",
		FgAccent:   "#e76b3e",
		FgDisabled: "#79715a",
		FgContrast: "#ebe5cf",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow: "#79715a",
		PaletteGreen:  "#79715a",
		PaletteRed:    "#888069",
		PaletteBlue:   "#888069",
	})
}
