// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-summer-night",
		Appearance: "dark",

		BgSelection: "#2a433a",
		BgContrast:  "#dfcbaa",
		BgNegative:  "#503d36",

		FgDefault:  "#dfcbaa",
		FgSubtle:   "#94a585",
		FgAccent:   "#bcb067",
		FgDisabled: "#71886c",
		FgContrast: "#001b1a",
		FgNegative: "#c88f7b",
		FgInfo:     "#89a88e",
		FgAdd:      "#96a85e",
		FgDelete:   "#c88f7b",

		PaletteYellow:      "#bcb067",
		PaletteGreen:       "#96a85e",
		PaletteRed:         "#c88f7b",
		PaletteBlue:        "#89a88e",
		PaletteMagenta:     "#ba929d",
		PaletteDarkMagenta: "#92768f",
	})
}
