// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-47-light",
		Appearance: "light",

		BgSelection: "#dfd6c9",
		BgContrast:  "#434b36",
		BgNegative:  "#fcd0cc",

		FgDefault:  "#20231b",
		FgSubtle:   "#5d684c",
		FgAccent:   "#00936b",
		FgDisabled: "#7a8568",
		FgContrast: "#e6dcd0",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow: "#ec5a00",
		PaletteGreen:  "#00936b",
		PaletteRed:    "#98a485",
		PaletteBlue:   "#98a485",
	})
}
