// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-fall-night",
		Appearance: "dark",

		BgSelection: "#382a23",
		BgContrast:  "#eac5b1",
		BgNegative:  "#5f3933",

		FgDefault:  "#eac5b1",
		FgSubtle:   "#c59174",
		FgAccent:   "#d68c00",
		FgDisabled: "#b58266",
		FgContrast: "#241710",
		FgNegative: "#e87a69",
		FgInfo:     "#d08c62",
		FgAdd:      "#95a483",
		FgDelete:   "#e87a69",

		PaletteYellow: "#d68c00",
		PaletteGreen:  "#95a483",
		PaletteRed:    "#e87a69",
		PaletteBlue:   "#d08c62",
	})
}
