// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-47-dark",
		Appearance: "dark",

		BgSelection: "#434b36",
		BgContrast:  "#e5cdad",
		BgNegative:  "#5f3a3a",

		FgDefault:  "#ffe7c7",
		FgSubtle:   "#7a8568",
		FgAccent:   "#3dc7a9",
		FgDisabled: "#6b765a",
		FgContrast: "#20231b",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow: "#fa8e3c",
		PaletteGreen:  "#3dc7a9",
		PaletteRed:    "#98a485",
		PaletteBlue:   "#98a485",
	})
}
