// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-spring-day",
		Appearance: "light",

		BgSelection: "#e2eae6",
		BgContrast:  "#385547",
		BgNegative:  "#e8cec5",

		FgDefault:  "#385547",
		FgSubtle:   "#55816a",
		FgAccent:   "#e49f1a",
		FgDisabled: "#62937a",
		FgContrast: "#d4dcd8",
		FgNegative: "#dd7e5d",
		FgInfo:     "#588dc1",
		FgAdd:      "#11b066",
		FgDelete:   "#dd7e5d",

		PaletteYellow: "#e49f1a",
		PaletteGreen:  "#11b066",
		PaletteRed:    "#dd7e5d",
		PaletteBlue:   "#588dc1",
	})
}
