// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-fall-day",
		Appearance: "light",

		BgSelection: "#ffe6d2",
		BgContrast:  "#422617",
		BgNegative:  "#e4c4bf",

		FgDefault:  "#422617",
		FgSubtle:   "#815137",
		FgAccent:   "#d9710b",
		FgDisabled: "#9b6a4f",
		FgContrast: "#f8ddc7",
		FgNegative: "#bf4d3f",
		FgInfo:     "#956d57",
		FgAdd:      "#6d7e57",
		FgDelete:   "#bf4d3f",

		PaletteYellow:      "#d9710b",
		PaletteGreen:       "#6d7e57",
		PaletteRed:         "#bf4d3f",
		PaletteBlue:        "#956d57",
		PaletteMagenta:     "#a26650",
		PaletteDarkMagenta: "#864d37",
	})
}
