// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-orange-dark",
		Appearance: "dark",

		BgSelection: "#111719",
		BgContrast:  "#e4edf0",
		BgNegative:  "#4b2829",

		FgDefault:  "#f2fafd",
		FgSubtle:   "#868e90",
		FgAccent:   "#fc8e06",
		FgDisabled: "#747c7e",
		FgContrast: "#030608",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow:      "#fc8e06",
		PaletteGreen:       "#868e90",
		PaletteRed:         "#9ea6a9",
		PaletteBlue:        "#9ea6a9",
		PaletteMagenta:     "#868e90",
		PaletteDarkMagenta: "#868e90",
	})
}
