// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-summer-day",
		Appearance: "light",

		BgSelection: "#ffeedd",
		BgContrast:  "#00280f",
		BgNegative:  "#e1cfc9",

		FgDefault:  "#00280f",
		FgSubtle:   "#26541c",
		FgAccent:   "#c67b36",
		FgDisabled: "#506e2c",
		FgContrast: "#f7e9d6",
		FgNegative: "#ac6e59",
		FgInfo:     "#5a8f65",
		FgAdd:      "#768c00",
		FgDelete:   "#ac6e59",

		PaletteYellow:      "#a19021",
		PaletteGreen:       "#768c00",
		PaletteRed:         "#ac6e59",
		PaletteBlue:        "#5a8f65",
		PaletteMagenta:     "#b67c8d",
		PaletteDarkMagenta: "#aa7fa5",
	})
}
