// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-spring-night",
		Appearance: "dark",

		BgSelection: "#313634",
		BgContrast:  "#d6d0c2",
		BgNegative:  "#593d38",

		FgDefault:  "#d6d0c2",
		FgSubtle:   "#82978c",
		FgAccent:   "#d1a762",
		FgDisabled: "#677e72",
		FgContrast: "#212523",
		FgNegative: "#ba6e5f",
		FgInfo:     "#99b9e6",
		FgAdd:      "#92d49a",
		FgDelete:   "#ba6e5f",

		PaletteYellow: "#d1a762",
		PaletteGreen:  "#92d49a",
		PaletteRed:    "#ba6e5f",
		PaletteBlue:   "#99b9e6",
	})
}
