// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-eink-dark",
		Appearance: "dark",

		BgSelection: "#2e2e2e",
		BgContrast:  "#c4c4c4",
		BgNegative:  "#543131",

		FgDefault:  "#dedede",
		FgSubtle:   "#8c8c8c",
		FgAccent:   "#d2b5bd",
		FgDisabled: "#7a7a7a",
		FgContrast: "#161616",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow:      "#8c8c8c",
		PaletteGreen:       "#8c8c8c",
		PaletteRed:         "#a4a4a4",
		PaletteBlue:        "#a4a4a4",
		PaletteMagenta:     "#8c8c8c",
		PaletteDarkMagenta: "#8c8c8c",
	})
}
