// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-mikado-dark",
		Appearance: "dark",

		BgSelection: "#2a435d",
		BgContrast:  "#c2cad3",
		BgNegative:  "#704a49",

		FgDefault:  "#e2ebf3",
		FgSubtle:   "#6c93bc",
		FgAccent:   "#f8ac3d",
		FgDisabled: "#5d84ac",
		FgContrast: "#1d364f",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow: "#f8ac3d",
		PaletteGreen:  "#6c93bc",
		PaletteRed:    "#8ab2dc",
		PaletteBlue:   "#76b1fc",
	})
}
