// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-terra-winter-day",
		Appearance: "light",

		BgSelection: "#f6f9fc",
		BgContrast:  "#1e2a37",
		BgNegative:  "#d4d4e8",

		FgDefault:  "#1e2a37",
		FgSubtle:   "#4f667c",
		FgAccent:   "#fa9916",
		FgDisabled: "#647d97",
		FgContrast: "#ebeff5",
		FgNegative: "#6e6ab2",
		FgInfo:     "#3578b8",
		FgAdd:      "#208295",
		FgDelete:   "#6e6ab2",

		PaletteYellow:      "#fa9916",
		PaletteGreen:       "#208295",
		PaletteRed:         "#6e6ab2",
		PaletteBlue:        "#3578b8",
		PaletteMagenta:     "#7968a9",
		PaletteDarkMagenta: "#665189",
	})
}
