// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-osman-light",
		Appearance: "light",

		BgSelection: "#e4dcd6",
		BgContrast:  "#4e463f",
		BgNegative:  "#ffd3cf",

		FgDefault:  "#38312b",
		FgSubtle:   "#6c6158",
		FgAccent:   "#1085fc",
		FgDisabled: "#897e74",
		FgContrast: "#f2eae2",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#897e74",
		PaletteGreen:       "#897e74",
		PaletteRed:         "#f1342d",
		PaletteBlue:        "#1085fc",
		PaletteMagenta:     "#897e74",
		PaletteDarkMagenta: "#897e74",
	})
}
