// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-default-dark-dimmed",
		Appearance: "dark",

		BgSelection: "#3e4349",
		BgContrast:  "#d0dad6",
		BgNegative:  "#633943",

		FgDefault:  "#e4eeea",
		FgSubtle:   "#7b8187",
		FgAccent:   "#4ec983",
		FgDisabled: "#6a6f76",
		FgContrast: "#20252a",
		FgNegative: "#e97292",
		FgInfo:     "#00b9c3",
		FgAdd:      "#4cb86a",
		FgDelete:   "#e97292",

		PaletteYellow: "#7b8187",
		PaletteGreen:  "#8d9399",
		PaletteRed:    "#8d9399",
		PaletteBlue:   "#6a6f76",
	})
}
