// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-mnml-mono-light",
		Appearance: "light",

		BgSelection: "#e0ddda",
		BgContrast:  "#3f3d3a",
		BgNegative:  "#ffd6d1",

		FgDefault:  "#181614",
		FgSubtle:   "#8e8c89",
		FgAccent:   "#2e2e2e",
		FgDisabled: "#b3b0ae",
		FgContrast: "#f1eeeb",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#b3b0ae",
		PaletteGreen:       "#b3b0ae",
		PaletteRed:         "#c6c3c1",
		PaletteBlue:        "#c6c3c1",
		PaletteMagenta:     "#b3b0ae",
		PaletteDarkMagenta: "#b3b0ae",
	})
}
