// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-default-light",
		Appearance: "light",

		BgSelection: "#a8afb5",
		BgContrast:  "#292e34",
		BgNegative:  "#ffd4e6",

		FgDefault:  "#0e1217",
		FgSubtle:   "#43484e",
		FgAccent:   "#2eaf6b",
		FgDisabled: "#646a70",
		FgContrast: "#c8ced5",
		FgNegative: "#ff50a7",
		FgInfo:     "#00abc1",
		FgAdd:      "#00a800",
		FgDelete:   "#ff50a7",

		PaletteYellow:      "#646a70",
		PaletteGreen:       "#757b81",
		PaletteRed:         "#53595f",
		PaletteBlue:        "#53595f",
		PaletteMagenta:     "#6791f1",
		PaletteDarkMagenta: "#df6989",
	})
}
