// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-paper-brown-dark",
		Appearance: "dark",

		BgSelection: "#4e463d",
		BgContrast:  "#cec2b3",
		BgNegative:  "#5b3737",

		FgDefault:  "#e8dccc",
		FgSubtle:   "#9b9082",
		FgAccent:   "#e5ddd0",
		FgDisabled: "#83796a",
		FgContrast: "#211f1c",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow:      "#9b9082",
		PaletteGreen:       "#9b9082",
		PaletteRed:         "#b4a99a",
		PaletteBlue:        "#b4a99a",
		PaletteMagenta:     "#9b9082",
		PaletteDarkMagenta: "#9b9082",
	})
}
