// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "<%= theme.meta.key %>",
		Appearance: "<%= theme.meta.appearance %>",

		BgSelection: "<%= theme.ui.bg.selection %>",
		BgContrast:  "<%= theme.ui.bg.contrast %>",
		BgNegative:  "<%= theme.ui.bg.negative %>",

		FgDefault:  "<%= theme.ui.fg.default %>",
		FgSubtle:   "<%= theme.ui.fg.subtle %>",
		FgAccent:   "<%= theme.ui.fg.accent %>",
		FgDisabled: "<%= theme.ui.fg.disabled %>",
		FgContrast: "<%= theme.ui.fg.contrast %>",
		FgNegative: "<%= theme.ui.fg.negative %>",
		FgInfo:     "<%= theme.ui.fg.info %>",
		FgAdd:      "<%= theme.ui.fg.add %>",
		FgDelete:   "<%= theme.ui.fg.delete %>",

		PaletteYellow: "<%= theme.palette.yellow %>",
		PaletteGreen:  "<%= theme.palette.green %>",
		PaletteRed:    "<%= theme.palette.red %>",
		PaletteBlue:   "<%= theme.palette.blue %>",
	})
}
